[package]
name = "dbms"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Database management system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "*"
futures = "*"

sql-parse.workspace = true
