[package]
name = "sql-parse"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "SQL parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone.workspace = true
